version: '3.9'
services:
  ark-server:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "arkmanager run"
    volumes:
      - ./arkmanager:/etc/arkmanager
      - ./Saved:/home/steam/ARK/ShooterGame/Saved
    ports:
      - "7778:7778"
      - "7778:7778/udp"
      - "27015:27015"
      - "27015:27015/udp"
    tty: true
    stdin_open: true
    